spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"